blueprint:
  name: Track Train by Schedule (AM & PM) – REST Command v7
  description: >
    Queries RTT station departures to find a specific train by time/destination.
    Supports multiple backup trains (comma-separated times), conditional detailed lookups,
    and notification preferences (only on issues, include train identity, platform changes).
    
    Requires ONE rest_command in configuration.yaml (rtt_service is optional):
    1. rtt_search: https://api.rtt.io/api/v1/json/search/{{ origin }}/to/{{ destination }}/{{ date }}/{{ time }}
  domain: automation

  input:
    days:
      name: Days of Week
      description: "Automation only runs on these days"
      selector:
        select:
          multiple: true
          mode: list
          options:
            - Monday
            - Tuesday
            - Wednesday
            - Thursday
            - Friday
            - Saturday
            - Sunday

    morning_station:
      name: Morning Origin Station (CRS)
      description: "Where you board (e.g., BKH)"
      selector:
        text: {}

    morning_destination:
      name: Morning Destination Station (CRS)
      description: "Where the train is going (e.g., CST)"
      selector:
        text: {}

    morning_scheduled:
      name: Morning Scheduled Time(s) (HHMM)
      description: "Comma-separated list of times to check in order (e.g., 0730,0745,0800). Will report on first available train."
      selector:
        text: {}

    morning_trigger_time:
      name: Morning Check Time
      description: "When to run the check (e.g., 07:20)"
      selector:
        time: {}

    evening_station:
      name: Evening Origin Station (CRS)
      description: "Where you board (e.g., CST)"
      selector:
        text: {}

    evening_destination:
      name: Evening Destination Station (CRS)
      description: "Where the train is going (e.g., BKH)"
      selector:
        text: {}

    evening_scheduled:
      name: Evening Scheduled Time(s) (HHMM)
      description: "Comma-separated list of times to check in order (e.g., 1717,1722,1730). Will report on first available train."
      selector:
        text: {}

    evening_trigger_time:
      name: Evening Check Time
      description: "When to run the check (e.g., 16:50)"
      selector:
        time: {}

    notify_device:
      name: Send Notifications To
      selector:
        device:
          filter:
            - integration: mobile_app

    notify_only_on_issues:
      name: Notify Only On Issues
      description: "If enabled, only send notifications for cancellations, delays, or platform changes. Suppress 'on time' messages."
      default: false
      selector:
        boolean: {}

    fetch_detailed_info:
      name: Fetch Detailed Service Info
      description: "If enabled, makes an additional API call to get full calling pattern. Only needed for advanced use cases."
      default: false
      selector:
        boolean: {}

trigger:
  - platform: time
    at: !input morning_trigger_time
    id: morning

  - platform: time
    at: !input evening_trigger_time
    id: evening

condition:
  - condition: template
    value_template: >
      {% set days = days_input %}
      {{ now().strftime('%A') in days }}

variables:
  days_input: !input days
  notify_device: !input notify_device
  notify_only_on_issues: !input notify_only_on_issues
  fetch_detailed_info: !input fetch_detailed_info
  
  # Inputs
  morning_origin: !input morning_station
  morning_dest: !input morning_destination
  morning_times_raw: !input morning_scheduled
  
  evening_origin: !input evening_station
  evening_dest: !input evening_destination
  evening_times_raw: !input evening_scheduled

  # Parse comma-separated times into lists
  morning_times: >
    {% set times = morning_times_raw.split(',') %}
    {{ times | map('trim') | map('replace', ':', '') | list }}
  
  evening_times: >
    {% set times = evening_times_raw.split(',') %}
    {{ times | map('trim') | map('replace', ':', '') | list }}

  # Determine search parameters based on trigger
  search_origin: >
    {{ morning_origin if trigger.id == 'morning' else evening_origin }}
  
  search_dest: >
    {{ morning_dest if trigger.id == 'morning' else evening_dest }}
    
  search_times: >
    {{ morning_times if trigger.id == 'morning' else evening_times }}

  today: "{{ now().strftime('%Y/%m/%d') }}"

action:
  # 1. Search for the first scheduled time
  - service: rest_command.rtt_search
    data:
      origin: "{{ search_origin }}"
      destination: "{{ search_dest }}"
      date: "{{ today }}"
      time: "{{ search_times[0] }}"
    response_variable: search_response

  - variables:
      search_data: "{{ search_response.content | from_json if search_response.content is string else search_response.content }}"
      
      # Find first matching service from the user's list
      found_service_json: >
        {% set ns = namespace(res='null') %}
        {% if search_data.services is defined %}
          {% for t in search_times %}
            {% for s in search_data.services %}
              {% if s.locationDetail.gbttBookedDeparture == t %}
                {% set ns.res = s | to_json %}
                {% break %}
              {% endif %}
            {% endfor %}
            {% if ns.res != 'null' %}{% break %}{% endif %}
          {% endfor %}
        {% endif %}
        {{ ns.res }}

      train_data: "{{ found_service_json | from_json }}"

  # 2. If no train found, notify and stop
  - if:
      - condition: template
        value_template: "{{ train_data is none }}"
    then:
      - domain: mobile_app
        type: notify
        device_id: !input notify_device
        message: >
          {% if search_data.error is defined %}
            ❌ API Error: {{ search_data.error }}
          {% else %}
            ❓ Could not find trains from {{ search_origin }} to {{ search_dest }} at {{ search_times | join(', ') }}.
          {% endif %}
      - stop: "No matching service found"

  # 3. Extract details
  - variables:
      loc: "{{ train_data.locationDetail }}"
      uid: "{{ train_data.serviceUid }}"
      id: "{{ train_data.trainIdentity | default('N/A') }}"
      
      # Status
      is_cancelled: "{{ loc.displayAs == 'CANCELLED_CALL' }}"
      platform: "{{ loc.platform | default('—') }}"
      platform_changed: "{{ loc.platformChanged | default(false) }}"
      cancel_reason: "{{ loc.cancelReasonShortText | default('Unknown') }}"
      
      # Times & Delay
      sched: "{{ loc.gbttBookedDeparture | default('') }}"
      actual: "{{ loc.realtimeDeparture | default('') }}"
      
      delay_min: >
        {% if sched and actual %}
          {% set s = strptime(sched | string, '%H%M') %}
          {% set a = strptime(actual | string, '%H%M') %}
          {% if s and a %}
            {% set d = (a - s).total_seconds() / 60 %}
            {{ (d + 1440 if d < -600 else d) | int }}
          {% else %}0{% endif %}
        {% else %}0{% endif %}

  # 4. Optional detailed info
  - if:
      - condition: template
        value_template: "{{ fetch_detailed_info }}"
    then:
      - service: rest_command.rtt_service
        data:
          uid: "{{ uid }}"
          date: "{{ today }}"
        response_variable: rtt_response

  # 5. Notify
  - choose:
      - conditions: "{{ is_cancelled }}"
        sequence:
          - domain: mobile_app
            type: notify
            device_id: !input notify_device
            message: >
              ❌ Train {{ sched }} ({{ id }}) is CANCELLED
              Reason: {{ cancel_reason }}

      - conditions: "{{ delay_min | int > 0 }}"
        sequence:
          - domain: mobile_app
            type: notify
            device_id: !input notify_device
            message: >
              ⚠️ Train {{ sched }} ({{ id }}) is DELAYED
              Expected: {{ actual }}
              Delay: {{ delay_min }} min
              Platform: {{ platform }}{% if platform_changed %} (⚠️ CHANGED){% endif %}

      - conditions: "{{ platform_changed and delay_min | int <= 0 and not is_cancelled }}"
        sequence:
          - domain: mobile_app
            type: notify
            device_id: !input notify_device
            message: >
              ⚠️ Train {{ sched }} ({{ id }}) - PLATFORM CHANGED
              New Platform: {{ platform }}
              Departure: {{ actual }}

    default:
      - if:
          - condition: template
            value_template: "{{ not notify_only_on_issues }}"
        then:
          - domain: mobile_app
            type: notify
            device_id: !input notify_device
            message: >
              ✅ Train {{ sched }} ({{ id }}) ON TIME
              Platform: {{ platform }}

mode: single
